name: Run download NOAA every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"   # каждые 30 минут. 
  workflow_dispatch:          # запуск вручную (по кнопке)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python 1.py
